### ISSUE TITLE
jade compiler script

### ISSUE THREAD

**Issue by fimble** [scotch/angular-brunch-seed#20] opened 2012-10-01 17:49 UTC
```
node_modules/.bin/jade app/index.jade --pretty --out app/assets/
node_modules/.bin/jade app/partials/ --pretty --out app/assets/partials/

rm app/index.jade && rm -rf app/partials/
```

this is really what you mean:

```
rm app/index.jade && rm -rf app/partials/
```

?!
maybe:

```
rm app/assets/index.html && rm -rf app/assets/partials/
node_modules/.bin/jade app/index.jade --pretty --out app/assets/
node_modules/.bin/jade app/partials/ --pretty --out app/assets/partials/
```

**Comment by fimble** [comment] 2012-10-01 17:51
And, funny, I can't clone this repo :)
because, github redirect me to my angular-brunch-seed-livescript !

**Comment by kylefinley** [comment] 2012-10-01 18:06
Hi @fimble,

With this commit f050cc075e2038a6ded3df05d563a32f22203cb1 jade templates were moved to `/app/partials`. It appears that `angular-brunch-seed-livescript` hasn't merged these changes -- that's why the `*.jade` files are still in the `/app/assets/partials` directory for you.

Does that resolve this issue?

-Kyle

**Comment by fimble** [comment] 2012-10-04 03:47
but why 'rm -rf /app/partials'? If /app/partials - jade sources, then this command will remove my sources, eh?

**Comment by kylefinley** [comment] 2012-10-04 04:05
Yes that script is intended for HTML users that have no intension of using Jade. I thought that it made sense to delete the files since they won't be using them. Maybe this could be more clear in the docs, what do you think the best way to word this would be?

And just to be clear if you're using Jade you no longer need to run a script in the background. As of the commit f050cc075e2038a6ded3df05d563a32f22203cb1 the jade files now compile automatically on save.

**Comment by fimble** [comment] 2012-10-04 05:26
Ok, now I understand what happens. But, sadly, static-jade-brunch didn't work here :(  And, in angular-seed-livescript too.

**Comment by fimble** [comment] 2012-10-04 05:27
try to delete app/assets/partials, and brunch build don't create this folder.

**Comment by fimble** [comment] 2012-10-04 05:29
index.html not created too.
only js/templates.js

**Comment by kylefinley** [comment] 2012-10-04 06:22
You are absolutely correct. It appears that a bug was introduced in static-jade-brunch v1.4.7. I have reverted to 1.4.5 and everything seems to be working now. Could you please test it?

I'll investigate further to see what the cause of this may be. Thank you for reporting this.

**Comment by kylefinley** [comment] 2012-10-05 00:45
staic-jade-brunch is working again. 582ffc993cb9ce8fb7a97d2e9905f64acec40df2 feel free to reopen this issue if you are still have problems.

**Closed as completed by kylefinley** 2012-10-05 00:45 UTC
