### ISSUE TITLE
here is my dumb question about project structure

### ISSUE THREAD

**Issue by cocodrino** [scotch/angular-brunch-seed#31] opened 2012-11-20 23:12 UTC
Hi..well..this is awkward but I've a little trouble..I'm trying use angular-ui...but I'm not sure where must I copy the UI modules...I suppose than not inside app/script because here is my coffee files...I'm tried copying this to vendors/scripts but this fail: "Uncaught Error: No module: app. ........ 

Sorry for this amazing noob question :(

**Comment by kylefinley** [comment] 2012-11-20 23:49
Hi @cocodrino,

No problem I appreciate you using angular-brunch-seed.

Yes, `vendor/scripts` would be the correct place to put angular-ui -- maybe the error is caused by the order in which angular-ui is loaded. You can specify the order in the [config.coffee file](https://github.com/scotch/angular-brunch-seed/blob/master/config.coffee#L15). Try listing the path to angular-ui files after `angular.js`. If that doesn't work could you please post the complete error message. Or could you put the code online somewhere that I could take a look?

Thank you,

Kyle

**Comment by kylefinley** [comment] 2012-12-11 16:16
@cocodrino,

I'm going to close this issue for now. Please feel free to reopen it, or create a new one, if I haven't solved your problem.

**Closed as completed by kylefinley** 2012-12-11 16:16 UTC
